sudo: false
language: rust
cache: cargo
before_script:
  - (cargo install cobalt-bin --vers 0.15.4 --force || true)

script:
  - cobalt build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  keep-history: true
  on:
    branch: source

